defmodule OwnershipAshChat.Repo.Migrations.AddRunOpenAnswers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:study_runs) do
      add :open_answers, :map, default: %{}
    end
  end

  def down do
    alter table(:study_runs) do
      remove :open_answers
    end
  end
end