defmodule OwnershipAshChat.Repo.Migrations.InitialSqlite do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:study_sessions, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :metadata, :map, default: %{}
      add :completed_at, :utc_datetime_usec
      add :started_at, :utc_datetime_usec
      add :status, :text, null: false
      add :topic_source_order, {:array, :text}
      add :case_id, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:study_sessions, [:case_id], name: "study_sessions_unique_case_id_index")

    create table(:study_runs, primary_key: false) do
      add :session_id,
          references(:study_sessions,
            column: :id,
            name: "study_runs_session_id_fkey",
            type: :uuid,
            on_delete: :delete_all,
            on_update: :update_all
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :modified_haiku, :text
      add :original_haiku, :text
      add :source_run_index, :bigint
      add :variant, :text
      add :completed_at, :utc_datetime_usec
      add :started_at, :utc_datetime_usec
      add :likert, :map, default: %{}
      add :final_haiku, :text
      add :transcript, {:array, :map}, default: []
      add :topic, :text
      add :ai_mode, :text
      add :topic_source, :text
      add :kind, :text, null: false
      add :run_index, :bigint
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `study_runs` table without the `study_runs_session_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:study_runs)

    drop_if_exists unique_index(:study_sessions, [:case_id],
                     name: "study_sessions_unique_case_id_index"
                   )

    drop table(:study_sessions)
  end
end