defmodule OwnershipAshChat.Repo.Migrations.AddModifiedLineIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:study_runs) do
      add :modified_line_index, :bigint
    end
  end

  def down do
    alter table(:study_runs) do
      remove :modified_line_index
    end
  end
end