defmodule OwnershipAshChat.Repo.Migrations.AddStudySessionAndRun do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:study_sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :case_id, :text
      add :topic_source_order, {:array, :text}
      add :status, :text, null: false, default: "in_progress"
      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:study_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :run_index, :bigint
      add :kind, :text, null: false, default: "writing"
      add :topic_source, :text
      add :ai_mode, :text
      add :topic, :text
      add :transcript, {:array, :map}, default: []
      add :final_haiku, :text
      add :likert, :map, default: %{}
      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :variant, :text
      add :source_run_index, :bigint
      add :original_haiku, :text
      add :modified_haiku, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :session_id,
          references(:study_sessions,
            column: :id,
            name: "study_runs_session_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(:study_runs, "study_runs_session_id_fkey")

    drop table(:study_runs)

    drop table(:study_sessions)
  end
end
