defmodule OwnershipAshChat.Repo.Migrations.AddSessionCaseIdIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:study_sessions) do
      modify :case_id, :text, null: false
    end

    create unique_index(:study_sessions, [:case_id], name: "study_sessions_unique_case_id_index")
  end

  def down do
    drop_if_exists unique_index(:study_sessions, [:case_id],
                     name: "study_sessions_unique_case_id_index"
                   )

    alter table(:study_sessions) do
      modify :case_id, :text, null: true
    end
  end
end
