defmodule OwnershipAshChat.Repo.Migrations.AddCaseNumber do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # SQLite cannot ALTER TABLE ADD a NOT NULL column without a default, so we give
    # it an empty-string DB default here. Every insert supplies a non-empty, unique
    # `case_number` (the attribute is required), so this default is never actually
    # used; it only satisfies SQLite's ADD COLUMN rule. The resource/snapshot record
    # no default, so no future codegen drift.
    alter table(:study_sessions) do
      add :case_number, :text, null: false, default: ""
    end

    create unique_index(:study_sessions, [:case_number],
             name: "study_sessions_unique_case_number_index"
           )
  end

  def down do
    drop_if_exists unique_index(:study_sessions, [:case_number],
                     name: "study_sessions_unique_case_number_index"
                   )

    alter table(:study_sessions) do
      remove :case_number
    end
  end
end